### ISSUE TITLE
单个模型融合结果时代码是否有错误

### ISSUE THREAD

**Issue by confstantine** [DataArk/CHIP2021-Task1-Top1#1]
https://github.com/DataArk/CHIP2021-Task1-Top1/blob/1a2954447b92c8ace2cc02a70ee558033ae37a46/predict/medbert.py#L725
这句话我猜作者您是要保存每个label的概率，但是这样的写法是不是写错了。
https://github.com/DataArk/CHIP2021-Task1-Top1/blob/1a2954447b92c8ace2cc02a70ee558033ae37a46/predict/medbert.py#L745
后面在针对most_长度大于1的情况下，为什么会选择概率总和最小的一个label作为结果呢？不应该是选择概率总和最大的label吗

**Comment by xiangking** [comment]
不好意思，这边注释留的是原始的注释，所以可能有点误导。其实这里做的是排序位置的一个加和，比如model1预测标签A，B，C的排序是0,1,2；model2预测标签A，B，C的排序是0,2,1;这里的做法是将它们的排序加起来，A：0，B：3，C: 3，这样求的其实就是最小值，也就是排序最靠前的标签。

**Comment by confstantine** [comment]
原来如此，感谢您的解答！
